using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace RomanReign
{
    /// <summary>
    /// This is the main class for the game. It is essentially a slightly modified version
    /// of the 'Game1.cs' file which is generated by the MonoGame project creation process.
    /// </summary>
    public class RomanReignGame : Game
    {
        // The default Game1 class only had a sprite batch to start with. We've added
        // a screen manager which we will use to manage all of our active screens for
        // us (including layering/overlaying screens on top of each other if we want).

        SpriteBatch m_spriteBatch;
        ScreenManager m_screenManager;

        /// <summary>
        /// The constructor is run when the program is launched. The only changes we have
        /// made to it are to specify our desired resolution and enable the mouse pointer.
        /// </summary>
        public RomanReignGame()
        {
            var graphics = new GraphicsDeviceManager(this)
            {
                PreferredBackBufferWidth = 1280,
                PreferredBackBufferHeight = 720,
                IsFullScreen = false
            };

            IsMouseVisible = true;

            Content.RootDirectory = "Content";
        }

        /// <summary>
        /// This function is run when it's time to load the content for our game. In it
        /// we create the sprite batch and screen manager objects, and we then tell the
        /// screen manager to immediately switch to our splash screen.
        /// </summary>
        protected override void LoadContent()
        {
            m_spriteBatch = new SpriteBatch(GraphicsDevice);
            m_screenManager = new ScreenManager(Content, m_spriteBatch);

            m_screenManager.SwitchTo(new SplashScreen(this, m_screenManager));
        }
        
        /// <summary>
        /// This function is run when the game is exiting.  It is possible that our screens
        /// might have code that needs to be run before the game exits, for example to save
        /// the game. By using the screen manager's UnloadContent function we can make sure
        /// that any such code *will* be run before the game exits.
        /// </summary>
        protected override void UnloadContent()
        {
            m_screenManager.UnloadContent();
        }
        
        /// <summary>
        /// In addition to updating all of the active screens, this function also runs
        /// the Begin() and End() functions in the input manager class.
        /// </summary>
        protected override void Update(GameTime gameTime)
        {
            Input.Begin();

            m_screenManager.Update(gameTime);

            Input.End();

            base.Update(gameTime);
        }

        /// <summary>
        /// This functions clears the screen and then tells the screen manager to
        /// draw all of the active screens.
        /// </summary>
        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            m_screenManager.Draw(gameTime);

            base.Draw(gameTime);
        }
    }
}
